# .github/workflows/main.yml
name: Main workflow

on:
  push:
    branches:
      - '**'

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11']

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
          pip install ruff==0.15.6

      - name: Ruff format check
        run: python -m ruff format --check backend/

      - name: Ruff lint check
        run: python -m ruff check backend/

  build_and_push_to_docker_hub:
    name: Push Docker image to DockerHub
    runs-on: ubuntu-latest
    needs: tests
    if: github.ref_name == 'main' || github.ref_name == 'master'

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push kittygram_backend to DockerHub
        uses: docker/build-push-action@v4
        with:
          context: ./backend/
          push: true
          tags: ${{ secrets.DOCKER_HUB_LOGIN }}/kittygram_backend:latest
      - name: Push kittygram_frontend to DockerHub
        uses: docker/build-push-action@v4
        with:
          context: ./frontend/
          push: true
          tags: ${{ secrets.DOCKER_HUB_LOGIN }}/kittygram_frontend:latest
      - name: Push kittygram_gateway to DockerHub
        uses: docker/build-push-action@v4
        with:
          context: ./nginx/
          push: true
          tags: ${{ secrets.DOCKER_HUB_LOGIN }}/kittygram_gateway:latest
  send_message:
    runs-on: ubuntu-latest
    if: always()
    needs:
      - tests
      - build_and_push_to_docker_hub

    steps:
      - name: Send message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Workflow: ${{ github.workflow }}
            Actor: ${{ github.actor }}
            Branch: ${{ github.ref_name }}
            Commit: ${{ github.event.commits[0].message }}
            Link: https://github.com/${{ github.repository }}/commit/${{ github.sha }}
            Tests: ${{ needs.tests.result }}
            Docker build: ${{ needs.build_and_push_to_docker_hub.result }}